### ISSUE TITLE
mboxlayer_api missing from sample_config

### ISSUE THREAD

**Issue by Kkevsterrr** [DataSploit/datasploit#103]
User Input: test_this_email@gmail.com
Looks like an EMAIL, running Email_OSINT...

---> Basic Email Check(s)..

Traceback (most recent call last):
  File "./emailOsint.py", line 233, in <module>
    main()
  File "./emailOsint.py", line 229, in main
    print_emailosint(email)
  File "./emailOsint.py", line 111, in print_emailosint
    basic_checks(email)
  File "datasploit/email_basic_checks.py", line 19, in basic_checks
    if cfg.mailboxlayer_api != "" and cfg.mailboxlayer_api != "XYZ" and cfg.mailboxlayer_api != "" and cfg.mailboxlayer_api != "XYZ":
AttributeError: 'module' object has no attribute 'mailboxlayer_api'

**Comment by 0xbadshah** [comment]
It seems that you have not set up the API key, **please add the API key** in the `config.py` file.

**Comment by Kkevsterrr** [comment]
Yup I understand that! I'm just alerting you to the fact that mailboxlayer_api is not in sample_config.py, so I didn't know I needed to set it until datasploit crashed

**Comment by 0xbadshah** [comment]
Thanks for raising the issue. Found that @upgoingstar committed the code recently (07202db) but failed to mention about the api key in the `config_sample.py`.

**Comment by upgoingstar** [comment]
Config_sample.py has not an entry for mailboxlayer_api. If you have already changed file name to config.py, please add this entry in the same.
