### ISSUE TITLE
User's git repos check. 

### ISSUE THREAD

**Issue by upgoingstar** [DataSploit/datasploit#105]
https://api.github.com/search/code?q=keyword+repo:reponame

use this in username osint, search for basic things after collecting all git repos belonging to user.

**Comment by 0xbadshah** [comment]
There are so many other APIs which would be helpful for OSINT. Check
- https://developer.github.com/v3/repos/
- https://developer.github.com/v3/search/
- https://developer.github.com/v3/users/

**Comment by upgoingstar** [comment]
I have written code for this, although its still in working phase and need to push this. 

Treating this issue as reminder for myself.

**Comment by upgoingstar** [comment]
solved in https://github.com/DataSploit/datasploit/commit/7c9018c3088c4fab662fb3cfe16ddc9db0e4805d
