### ISSUE TITLE
Run mongo on localhost

### ISSUE THREAD

**Issue by kartikeyap** [DataSploit/datasploit#108]
Mongo is intended to be run in a trusted environment so generally I would think that it's limited to loopback interface. Documentation (step by step guide) says that you start you db as:

`mongod --dbpath datasploitDb`

[Suggestion] Documentation can be updated to encourage users to start mongo on loopback i.e.

`mongod --dbpath datasploitDb --bind_ip 127.0.0.1`

**Comment by upgoingstar** [comment]
Thats the correct way to start mongodb. Thanks for the shout. 

By the way, mongodb thing is not required anymore, since GUI is no more supported.
