### ISSUE TITLE
file is missing

### ISSUE THREAD

**Issue by dineshpdk** [DataSploit/datasploit#110]
Core File is missing while downloading the datasploit files from github

**Comment by dineshpdk** [comment]
Downloading by using the corresponding URL.
git clone https://github.com/upgoingstar/datasploit.git

**Comment by 0xbadshah** [comment]
What do you mean by core file ?
BTW try using `git clone https://github.com/DataSploit/datasploit.git`

**Comment by dineshpdk** [comment]
Its a directory downloaded with the datasploit package...
By the way i tried downloading the file by using this 
git clone https://github.com/DataSploit/datasploit.git

**Comment by 0xbadshah** [comment]
I am not understanding your problem. Please be brief about it. After you clone the repository, just do `cd datasploit` and starting using datasploit.

**Comment by upgoingstar** [comment]
Please re open if issues still exists.
