### ISSUE TITLE
Issue during brew services restart rabbitmq

### ISSUE THREAD

**Issue by Nacircle** [DataSploit/datasploit#111]
I am facing issue during this command 'brew services restart rabbitmq'

error output : 
sh: 1: list: not found
sh: 1: list: not found
sh: 1: list: not found
Error: Formula `rabbitmq` is not installed.

but I can restart the Rabbit server and able to open the Rabbit console in browser..

Thanks,
Nand

**Comment by 0xbadshah** [comment]
GUI version of Datasploit is not supported as of now.

**Comment by Nacircle** [comment]
My bad :( ... However thank you for Ur reply , looking forward to see the GUI version soon....
