### ISSUE TITLE
Manage.py missing 

### ISSUE THREAD

**Issue by Nacircle** [DataSploit/datasploit#112]
Dear Team,

I followed the Datasploit installation document procedure and finally got stuck at executing manage.py with the api file. I found  manage.py is missing in the source folder but I could see the earlier version has the manage.py and the latest requirements.txt also missing some dependencies compared with the older version. Can you please help me out to pass through this challenge ?

Note : I found the existence of the manage.py in older version in google search page which is attached here

Regards,
Nand
![screenshot-manage_py-datsp](https://cloud.githubusercontent.com/assets/26647176/24296589/a995403a-10c5-11e7-970e-af820a087dad.JPG)

**Comment by 0xbadshah** [comment]
The early GUI version had some issues within itself and also the development of different modules were not updated in the GUI version. So @upgoingstar deleted the django GUI version in the commit: 8128b07
By the way the _documentation is not completely up to date_ and is still under development.

**Comment by Nacircle** [comment]
Ok got it. Thanks a lot.

Regards,
Nanda
