### ISSUE TITLE
Irrelevant dependencies !

### ISSUE THREAD

**Issue by 0xbadshah** [DataSploit/datasploit#117]
There are some irrelevant dependencies in the modules. Follow this issue to keep track of such dependencies which are not required.

**Comment by 0xbadshah** [comment]
**`domainOsint.py`**:

- [Line 52](https://github.com/DataSploit/datasploit/blob/master/domainOsint.py#L52)
`from email_fullcontact import fullcontact` is not required

**Comment by upgoingstar** [comment]
solved in V_1.0
