### ISSUE TITLE
Double terminal logo print !

### ISSUE THREAD

**Issue by 0xbadshah** [DataSploit/datasploit#118]
[Line 519](https://github.com/DataSploit/datasploit/blob/master/domainOsint.py#L519) in `domainOsint.py` prints the logo in terminal. 
Also [Line 27](https://github.com/DataSploit/datasploit/blob/master/datasploit.py#L27) in `datasploit.py` prints the logo in terminal. 
If a user runs `$ ./datasploit.py somewebsite.tld`, he will get the logo printed twice !

**Suggestion:** Delete the `printart()` from `domainOsint.py` which makes the logo printing centralized and restricted to `datasploit.py`

**Comment by upgoingstar** [comment]
@Chan9390 - datasploit.py is not a very useful thing as of now. We are waiting to release the new cleaned up, more structured version of DataSploit. It will be addressed in that release. 

Thanks for the shout.
