### ISSUE TITLE
Unicode Encoding and total_results in domain_pastes.py

### ISSUE THREAD

**Issue by mainframed** [DataSploit/datasploit#123]
Two quick fixes in `domain_pastes.py`:

### Line 41

https://github.com/DataSploit/datasploit/blob/master/domain_pastes.py#L41

Causes unicode error for non ascii characters. Change:

From
```Python
print "Title: %s\nURL: %s\nSnippet: %s\n" % (x['title'], colorize(x['link']), colorize(x['snippet']))
```
To
```Python
snippet = x['snippet'].encode('ascii', 'ignore').decode('ascii')
title = x['title'].encode('ascii', 'ignore').decode('ascii')
print "Title: %s\nURL: %s\nSnippet: %s\n" % (title, colorize(x['link']), colorize(snippet))
```
This prevents it from erroring out when encountering unicode characters (it removes them). 

### Line 59

https://github.com/DataSploit/datasploit/blob/master/domain_pastes.py#L59

the `google_search` function returns a tuple ('total results', 'results') but your comparison is done against numbers. A simple fix:

From:
```Python
total_results = google_search(domain, 1)
```
To:
```Python
total_results = google_search(domain, 1)[0]
```

**Comment by KunalAggarwal** [comment]
@mainframed Thanks for the inputs. Incorporated in commit 0c2b10083c6a7a865e914d04e10225a57b9b2c78. Marking as closed.
