### ISSUE TITLE
Enumerate subdomains from Certificate Transparency Project

### ISSUE THREAD

**Issue by upgoingstar** [DataSploit/datasploit#125]
https://www.google.com/transparencyreport/https/ct/ > json API, should be easy to write.

**Comment by meme-lord** [comment]
Added it, here's my pull request: https://github.com/DataSploit/datasploit/pull/138

**Comment by upgoingstar** [comment]
Changes made in commit https://github.com/DataSploit/datasploit/commit/550a7ff9e9b52295e9f354523b7a9c5496957f8a
