### ISSUE TITLE
Shouldn't modules requiring API Keys give error messages instead of breaking?

### ISSUE THREAD

**Issue by meme-lord** [DataSploit/datasploit#139]
Just started playing around with datasploit today, haven't set all the api keys but shouldn't there be some checks that  see if the api key isnt blank or that it's set before trying to use them?
I don't mind implementing it just want to know the opinon's of other contributors.
I think the best way to implement it would be having a function like is_api_key_set("api_key_variable_name") checks that the variable exists its != "" and then call that in the modules.
If it doesn't exist it will print something like "[!] ERROR: API Key not set for XYZ in config.py"

**Comment by meme-lord** [comment]
Also if you did it this way you could just call config_sample.py config.py and you wouldn't have the confusion when modules fail to import a non-existant config.

**Comment by upgoingstar** [comment]
solved in https://github.com/DataSploit/datasploit/commit/8e5fa0dcffdee7bbb61496872f6f74c00f04c89e
