### ISSUE TITLE
ZoomEye error

### ISSUE THREAD

**Issue by fiorenzi** [DataSploit/datasploit#145]
on ZoomEye query get this erros:

---> Finding hosts from ZoomEye

Traceback (most recent call last):
  File "./domainOsint.py", line 17, in <module>
    run(domain, options.output)
  File "./domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/opt/datasploit/osint_runner.py", line 29, in run
    data = x.main(m_input)
  File "/opt/datasploit/domain/domain_zoomeye.py", line 42, in main
    zoomeye_results = search_zoomeye(domain)
  File "/opt/datasploit/domain/domain_zoomeye.py", line 31, in search_zoomeye
    zoomeye_token = get_accesstoken_zoomeye(domain)
  File "/opt/datasploit/domain/domain_zoomeye.py", line 25, in get_accesstoken_zoomeye
    access_token1 = responsedata['access_token']
KeyError: 'access_token'

**Comment by upgoingstar** [comment]
I cnt generate the access_token even with postman/burp/manually. I either get 
{"url": "https://www.zoomeye.org", "message": "Upgrading...", "error": "bad_request"}

of I get 500 internal Server error. 

Even the zoomeye python library don't seem to be working as it prints a blank access token. Need to look into the same, till then you can disable the module using 'ENABLED = False'

**Comment by spmedia** [comment]
Getting this same error.

**Comment by spmedia** [comment]
Also get the same error for Shodan once I set domain_zomeeye.py to False.

 ---> Searching in Shodan:

Traceback (most recent call last):
  File "datasploit.py", line 55, in <module>
    main(user_input, options.output)
  File "datasploit.py", line 43, in main
    domainOsint.run(user_input, output)
  File "/root/clone/domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/root/clone/osint_runner.py", line 31, in run
    x.output(data, m_input)
  File "/root/clone/domain/domain_shodan.py", line 39, in output
    if data[1] == "INVALID_API":
KeyError: 1

I have a valid API key set in config.py for shodan_api.

**Comment by upgoingstar** [comment]
the Shodan one is resolved now. please do a git pull. 

Zoomeye one is something I cannot re-create using Python. I will look into it as soon as possible.

**Comment by Demigoddd** [comment]
How to fix Zoomeye?
my error → <html><title>500: Internal Server Error</title><body>500: Internal 1 Server Error</body></html>.....
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by bardicknowledge** [comment]
Tried to curl the ZoomEye request according to the API documentation, and got the Upgrading... error just the same as what the module returned.  The module just needs to handle the error when a service isn't responding as expected.

**Comment by bardicknowledge** [comment]
Quick and dirty fix (starting in domain_zoomeye.py:43):
```
def main(domain):
    if cfg.zoomeyepass != "" and cfg.zoomeyeuser != "":
        try:
            zoomeye_results = search_zoomeye(domain)
            return json.loads(zoomeye_results)
        except:
            return [False, "UNSPECIFIED_ERROR"]
    else:
        return [False, "INVALID_API"]
```

**Comment by iaelectronic** [comment]
From the end of August 2017 it is not possible ZoomEye neither in the API nor in the browser is thrown every time you try to make a query jump "Upgrading ..."

I have sent some email to know if it is their problem, but they do not respond ...

![image](https://user-images.githubusercontent.com/31543424/30519920-c84d5cca-9ba2-11e7-957d-d19dc32c73a8.png)
