### ISSUE TITLE
Must downgrade lxml to 3.6.0?

### ISSUE THREAD

**Issue by antonely93** [DataSploit/datasploit#178]
Hello,
i have error when installing the requirements, ... 
Failed building wheel for lxml
Foun existing installation: lxml 3.8.0
......
At the end have this:
Can't rollback lxml, nothing uninstalled.
Command "/usr/bin/python -u -c "import setuptools, tokenize;file='/tmp/pip-build-CUr3cA/lxml/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-TD7g2p-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-CUr3cA/lxml/

i'm on kali: Linux kali 4.12.0-kali1-686-pae #1 SMP Debian 4.12.6-1kali6 (2017-08-30) i686 GNU/Linux

If i must downgrade to lxml 3.6.0 please how i do that?

Thanks

**Comment by anantshri** [comment]
question to be asked is is lxml 3.6.0 a requirement. since 3.8.0 is out why not use it.

@antonely93 you cna try one thing. in your requirements.txt file there is a line 
```
lxml==3.6.0
```

try changing that to
```
lxml
```

then try running the pip install again. IF that helps then you don't need lxml that specific version.

**Comment by antonely93** [comment]
too late :) i already remove the 3.8.0 and install the 3.6.0 and it is working fine now

**Comment by upgoingstar** [comment]
Closing this. We are going to do dummy installation run on multiple boxes to see the challenges while installing datasploit and any observed issues will be raised and fixed.
