### ISSUE TITLE
Does the website exist ?

### ISSUE THREAD

**Issue by 0xbadshah** [DataSploit/datasploit#18]
Does the website given in domainOsint.py "**www.datasploit.info**" really exist ?
https://github.com/upgoingstar/datasploit/blob/master/domainOsint.py#L89

**Comment by 0xbadshah** [comment]
Website exists, but inactive.
https://who.is/whois/datasploit.info

**Comment by Chan9390** [comment]
Website exists, but inactive.
https://who.is/whois/datasploit.info

**Comment by Chan9390** [comment]
Website exists, but inactive.
https://who.is/whois/datasploit.info

**Comment by upgoingstar** [comment]
Hello mate, 

Website will be up soon. Better to launch in one go pushing a raw version.
