### ISSUE TITLE
config_sample.py file error

### ISSUE THREAD

**Issue by sudhamani85** [DataSploit/datasploit#195]
Hi,

I have configured as suggested but when i run the module i get the following error

[+] Looks like a new setup, setting up the config file.
Traceback (most recent call last):
  File "datasploit.py", line 87, in <module>
    main(sys.argv[1:])
  File "datasploit.py", line 43, in main
    shutil.copyfile(config_sample_path,config_file_path)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:

Please help me resolve this

**Comment by anantshri** [comment]
Was trying to figure out the issues seems like https://github.com/DataSploit/datasploit/commit/d8f7221f768e819633330c17773da6d91d580089 fix is the cause of the bug.

getcwd will pick current directory and we need to look for config_sample and config files at the datasploit install location which should be same as the location of the file datasploit.py.
