### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by eigenstein** [DataSploit/datasploit#204]
If you are going to close Issues (#159 and #166), please be so kind as to supply or reference the solution or resolution. I still have the same error running domainOsint.py.

**Comment by KunalAggarwal** [comment]
Are you sure, you've taken a git pull to get the latest code from the repository? These issues were fixed in recent commits.

**Comment by eigenstein** [comment]
Yes, fresh git pull that day. Will try again.

**Comment by eigenstein** [comment]
json errors are gone. Yay!
