### ISSUE TITLE
AttributeError: 'list' object has no attribute 'strftime'

### ISSUE THREAD

**Issue by eigenstein** [DataSploit/datasploit#207]
---> Finding Whois Information.
Traceback (most recent call last):
  File "domainOsint.py", line 17, in <module>
    run(domain, options.output)
  File "domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/usr/share/datasploit/osint_runner.py", line 30, in run
    x.output(data, m_input)
  File "/usr/share/datasploit/domain/domain_whois.py", line 34, in output
    data['expiration_date'] = data['expiration_date'].strftime('%m/%d/%Y')
AttributeError: 'list' object has no attribute 'strftime'

**Comment by morgendave** [comment]
python-whois actually would return the dates with list, not guaranteed to be single datetime. Quick fix would be to check it.

**Comment by 0xbadshah** [comment]
Hey @eigenstein , please try pulling the latest code and check if you are facing the same issue.

**Comment by eigenstein** [comment]
Issue is now gone.
