### ISSUE TITLE
Googlepdf and ZoomEye marked as disabled

### ISSUE THREAD

**Issue by cikasole** [DataSploit/datasploit#228]
### Host System

- OS : Kali Linux 2017.3
- Python version (`python --version`) : Python 2.7.14+

### Error Description

When I start the tool on any domain, I get the following output>
      
  "Skipping Googlepdf because it is marked as disabled."
  "Skipping Zoomeye because it is marked as disabled."

I followed the instructions on how to generate API keys strictly (as given at http://datasploit.readthedocs.io/en/latest/apiGeneration/). 

Now I can not find how to activate Googlepdf and ZoomEye.

Best regards,

sole

**Comment by 0xbadshah** [comment]
Hey @cikasole ,

The GooglePDF and ZoomEye modules are disabled by default because the modules are not stable as of now.

**Comment by cikasole** [comment]
Hi @Chan9390 ,
Thank you for your explanation. I was searching on their web sites for the solution how to activate the API keys. Now I can stop.

**Comment by marionapous** [comment]
How do we enable them manually?
