### ISSUE TITLE
Missing module error with ./datasploit.py

### ISSUE THREAD

**Issue by Sjuuls** [DataSploit/datasploit#229]
Please provide the following details.

### Host System

- OS :  Kali Linux 2017.3
- Python version (`python --version`) :  2.7.14+

### Error Description

Even though I have filled in the config.py and did the pip requirements install on both the txt file and just the pip install datasploit, it doesn't seem to go past this message.

Did a pip freeze to the requirements.txt too, still same error.

```
root@kali:~/DataSploit# ./datasploit.py
You are missing a module for Datasploit. Please install them using: 
pip install -r requirements.txt
```

Please provide the details of the error. Try to provide the **output** and also **steps to reproduce** (if possible).

If you cloned Datasploit, also provide the output of `git log -n 1 --pretty=format:"%B"`.

**Comment by ishamfazal** [comment]
have you tried entering this command **pip install -r requirements.txt**

**Comment by Sjuuls** [comment]
Yes I have, it didn't have any effect.

**Comment by Sjuuls** [comment]
these are the commands i did:

pip install -r requirements.txt
pip install datasploit
pip freeze > requirements.txt

I updated Kali, I updated the config file with my API's, I gave the datasploit folder full permission

Nothing seemed to have worked so far.

**Comment by hACkABUS** [comment]
it may be that you have python 3 installed aswell and pip configured to run with python 3 
use this command

python -m pip install -U --force-reinstall pip (this will force pip to use python 2.7
then reinstall requirements.txt
then run python datasploit.py -i (then whatever website address)
hope this helps

**Comment by Sjuuls** [comment]
Sorry for the late response.

I tried what you said, the results are as follows:

> root@kali:~/DataSploit# python -m pip install -U --force-reinstall pip
> Collecting pip
>   Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
>     100% |████████████████████████████████| 1.3MB 1.0MB/s 
> Installing collected packages: pip
>   Found existing installation: pip 9.0.1
>     Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
> Successfully installed pip-9.0.1
> root@kali:~/DataSploit# pip install -r requirements.txt
> Requirement already satisfied: adns-python==1.2.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
> Requirement already satisfied: altgraph==0.15 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
> Requirement already satisfied: zenmap==7.60 in /usr/lib/python2.7/dist-packages (from -r 
> Requirement already satisfied: zope.interface==4.3.2 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 275))
> Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages/setuptools-27.3.0.post20171227-py2.7.egg (from PyInstaller==3.3.1->-r requirements.txt (line 170))
> Requirement already satisfied: argparse in /usr/lib/python2.7 (from pythonwhois==2.4.3->-r requirements.txt (line 202))
> root@kali:~/DataSploit# ./datasploit.py www.sample.com
> You are missing a module for Datasploit. Please install them using: 
> pip install -r requirements.txt
> root@kali:~/DataSploit# python datasploit.py -i www.sample.com
> You are missing a module for Datasploit. Please install them using: 
> pip install -r requirements.txt


So alas, it didn't really do what i was hoping for.. Hope there will be some fix for it or that it'll be working with Python 3 soon, maybe that will fix it.

P.S.: I cut some lines of the 'already satisfied requirements' since my last pip freeze gave the requirements.txt  ~300 lines, so kind of unnecessary to go through all of them, I can promise you, thay are all installed and thus 'satisfied'.

**Comment by 0xbadshah** [comment]
Hey @Sjuuls , sorry for being late to comment. Execute `pip install --upgrade --force-reinstall -r requirements.txt` and try running Datasploit. If any issues please comment.

**Comment by Sjuuls** [comment]
Hey @Chan9390 , Thank you for the reply. It worked! I still got an error after the force reinstall:

> Traceback (most recent call last):
>   File "/usr/local/bin/pip", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 233, in main
>     return command.main(cmd_args)
>   File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 252, in main
>     pip_version_check(session)
>   File "/usr/local/lib/python2.7/dist-packages/pip/utils/outdated.py", line 102, in pip_version_check
>     installed_version = get_installed_version("pip")
>   File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 838, in get_installed_version
>     working_set = pkg_resources.WorkingSet()
>   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
>     self.add_entry(entry)
>   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
>     for dist in find_distributions(entry, True):
>   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
>     if metadata.has_metadata('PKG-INFO'):
>   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
>     return self.egg_info and self._has(self._fn(self.egg_info, name))
>   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
>     return zip_path in self.zipinfo or zip_path in self._index()
>   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
>     return self._zip_manifests.load(self.loader.archive)
>   File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
>     mtime = os.stat(path).st_mtime
> OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/setuptools-27.3.0.post20171227-py2.7.egg'

But it worked non the less!

So thank you very much for that! Might be a great help for others if they end up with the same problem to put it in the readme :-) 

Kind Regards Sjuuls

**Comment by 0xbadshah** [comment]
Whats your `pip` version (`pip --version`) ?

**Comment by Sjuuls** [comment]
```
root@kali:~/DataSploit# pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

**Comment by 0xbadshah** [comment]
How about executing `pip install --upgrade setuptools` ?

**Comment by Sjuuls** [comment]
```
root@kali:~/DataSploit# pip install --upgrade setuptools
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages
```

**Comment by 0xbadshah** [comment]
Still getting the error ??

**Comment by Sjuuls** [comment]
No it literally gave me the above output :)

**Comment by Sjuuls** [comment]
I could try and do: `pip install --upgrade --force-reinstall -r requirements.txt` again?
See if that rings any alarmbells

Edit: Just tried it, seems it solved itself? No errors anymore, yay!

**Comment by 0xbadshah** [comment]
Try `apt-get install -y python-setuptools`

**Comment by Sjuuls** [comment]
It's already the newest :)

```
python-setuptools is already the newest version (38.2.4-1).
python-setuptools set to manually installed.
```

I think we've solved it, or at least you did! Cheers!

**Comment by 0xbadshah** [comment]
Did that work ??

**Comment by Sjuuls** [comment]
Yes it did! I think `pip install --upgrade --force-reinstall -r requirements.txt` already did the job and there was a bit of a buggy moment, but when i reran it , it did great! So thank you very much! 

Kind regards,

Sjuuls

**Comment by 0xbadshah** [comment]
Cool. We made it together :+1: 
Thanks for taking your time to raise an issue and cooperate to find the solution. Appreciate that.
