### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strftime' in domain_whois.py

### ISSUE THREAD

**Issue by DocKali** [DataSploit/datasploit#232]
Please provide the following details.

### Host System

- OS : Kali
- Python version (`python --version`) : 2.7.14+

### Error Description

When I try to run Datasploit against a target, everything is good until the tool came to domain_whois.py. Here, I have the following : 

File "/etc/datasploit/domain/domain_whois.py", line 34, in output
    data[k] = date.strftime('%m/%d/%Y')
AttributeError: 'NoneType' object has no attribute 'strftime'

What can I do to solve this problem?

Thank you for your help.

If you cloned Datasploit, also provide the output of `git log -n 1 --pretty=format:"%B"`.

**Comment by 0xbadshah** [comment]
Hey @DocKali , so the error output says that `date` is `None`. Will raise a PR in some time to add exception handling.

(If you could disclose your target it would be easier to replicate the situation locally and improve the code. You can ignore this suggestion if it is sensitive data)

**Comment by DocKali** [comment]
If I understand, there is no date in the Whois and that's why domain_whois.py crashes ?

Unfortunately I can't disclose the target with whom I have this problem. I'll try with some other target, less sensitive, and I'll come back to you if I reproduce the same error.

Thank you very much for your answer, please let me know when you raise the PR who'll solve this problem.

**Comment by ishamfazal** [comment]
@DocKali hi, this issue has been fixed on #227 please update your branch and retry

**Comment by DocKali** [comment]
Thanks a lot @ishamfazal, I update the branch and relaunch the test.
