### ISSUE TITLE
Module missing

### ISSUE THREAD

**Issue by MelissaMV** [DataSploit/datasploit#233]
### Host System

- OS :  Kali Linux
- Python version (`python --version`) :  Python 2.7.14

root@kali:~# git clone https://github.com/DataSploit/datasploit.git

Cloning into 'datasploit'...
remote: Counting objects: 1921, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1921 (delta 1), reused 3 (delta 0), pack-reused 1915
Receiving objects: 100% (1921/1921), 11.78 MiB | 2.44 MiB/s, done.
Resolving deltas: 100% (995/995), done.

root@kali:~# 

I did run the "pip install -r requirements.txt" but im getting the following error:

### Error Description

root@kali:~/datasploit# ls

active_default_file_check.py  datasploit.py   __init__.py reports
active_scan.py dep_check.py ip  requirements.txt
base.html docs ipOsint.py roadmap.txt
check_urls.txt domain LICENSE username
config.py domainOsint.py mkdocs.yml usernameOsint.py
contributors.txt emailOsint.py osint_runner.py vault.py
datasploit_config.py emails README.md

root@kali:~/datasploit# python datasploit.py

You are missing a module for Datasploit. Please install them using: 
pip install -r requirements.txt

root@kali:~/datasploit#

**Comment by 0xbadshah** [comment]
Hey @MelissaMV, try `pip install --upgrade --force-reinstall -r requirements.txt` and then execute Datasploit.

**Comment by MelissaMV** [comment]
@Chan9390 Thank you! it worked :)

**Comment by 0x90n** [comment]
To second this, I found the following fix also works for certain Kali builds.

pip install -r requirements.txt --upgrade --ignore-installed

**Comment by 0xbadshah** [comment]
Hey @MelissaMV can you close the issue ?
