### ISSUE TITLE
Wappalyzer issue - no module named Wappalyzer

### ISSUE THREAD

**Issue by iancnorden** [DataSploit/datasploit#25]
Ian@Box:~/Downloads/datasploit-master$ cat requirements.txt | grep Wapp
python-Wappalyzer==0.2.2
Ian@Box:~/Downloads/datasploit-master$ pip list | grep Wapp
python-Wappalyzer (0.2.2)
Ian@Box:~/Downloads/datasploit-master$ 
Ian@Box:~/Downloads/datasploit-master$ python domainOsint.py google.com
Traceback (most recent call last):
  File "domainOsint.py", line 35, in <module>
    from Wappalyzer import Wappalyzer, WebPage
ImportError: No module named Wappalyzer
Ian@Box:~/Downloads/datasploit-master$ 

Tinkering a bit I can get the wappalyzer-python-0.1.2 package down and begin renaming your froms in domainOsint.py to call that version but run into other errors. Am I missing something preventing this from working with the properly referenced python-Wappalyzer version?

**Comment by wifiuk** [comment]
i type in sudo pip install python-wappalyzer

**Comment by iancnorden** [comment]
As the documentation and requirements list states python-Wappalyzer==0.2.2 is required, above I was able to show the installed version matches requirements listed version.

**Comment by upgoingstar** [comment]
I believe python-Wappalyzer==0.2.2 should work fine, however can you try to uninstall the same and then run

sudo pip install python-Wappalyzer

Let me know if it still doesnt works.

**Comment by krasikotsev** [comment]
I also have a Python Wappalyzer error, but it's a little bit different:
->Trying Wapalyzer on HTTP: 
[-] HTTP connection was unavailable
->Trying Wapalyzer on HTTPS: 
[-] HTTP connection was unavailable

I have installed the wappalyzer the same way like wifiuk.
Any ideas would be appreciated.

**Comment by Vancer** [comment]
This worked perfectly fine for me: `pip install python-Wappalyzer==0.2.2`

**Comment by upgoingstar** [comment]
Awesome.

**Comment by moschinoZ** [comment]
it need python 2.7 ,not  python3
