### ISSUE TITLE
configobj.ConfigObjError: Parsing failed with several errors.

### ISSUE THREAD

**Issue by manishj1996** [DataSploit/datasploit#274]
### Host System

- OS : 4.17.0-kali1-amd64 
- Python version (`python --version`) : Python 2.7.15

### Error Description
```
[-] Skipping Urlscanio because it is marked as disabled.
[-] Skipping Zoomeye because it is marked as disabled.
[-] Skipping Googlepdf because it is marked as disabled.

[-] Please configure respective API Keys for this module.


---> Searching Github for domain results

Traceback (most recent call last):
  File "domainOsint.py", line 17, in <module>
    run(domain, options.output)
  File "domainOsint.py", line 9, in run
    osint_runner.run("domain", "domain", domain, output)
  File "/root/Desktop/tools/datasploit-master/osint_runner.py", line 28, in run
    data = x.main(m_input)
  File "/root/Desktop/tools/datasploit-master/domain/domain_github.py", line 31, in main
    if vault.get_key('github_access_token') != None:
  File "/root/Desktop/tools/datasploit-master/vault.py", line 9, in get_key
    config = ConfigObj(config_file)
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 1318, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 12.
```

I am getting this error while running any module of datasploit. I have added all the API keys in config.py

**Comment by PolarBearGod** [comment]
I am now experiencing this exact issue. What was done to close this?

edit:

Fixed the issue by using the updated config_sample.py. When migrating from the dvopsway/datasploit repository, that config_sample.py is outdated.

**Comment by hackerboijohn** [comment]
> I am now experiencing this exact issue. What was done to close this?
> 
> edit:
> 
> Fixed the issue by using the updated config_sample.py. When migrating from the dvopsway/datasploit repository, that config_sample.py is outdated.



I have the updated config_sample.py with fresh api keys but still it gives the same error
