### ISSUE TITLE
Extensive use of tab space \t

### ISSUE THREAD

**Issue by 0xbadshah** [DataSploit/datasploit#29]
Most of the scripts has `\t\t\t` prefixed to the display messages. When executing it on Ubuntu (bash), the _output messages are quite odd_ because of the tabs.

Below is a screenshot of `domain_emailhunter.py` module on Ubuntu terminal:
![upload](https://cloud.githubusercontent.com/assets/12944530/17559735/e4703fc4-5f3c-11e6-8882-4b816a1047cb.jpg)

I would suggest **using a space instead of the tabs**

**Comment by upgoingstar** [comment]
Most of the tabs are removed, please point to any specific tab (if any).

**Comment by 0xbadshah** [comment]
**`usernameOsint.py`** :

- [Line 276](https://github.com/DataSploit/datasploit/blob/master/usernameOsint.py#L276)
- [Line 298](https://github.com/DataSploit/datasploit/blob/master/usernameOsint.py#L298)
- [Line 306](https://github.com/DataSploit/datasploit/blob/master/usernameOsint.py#L306)

**Comment by 0xbadshah** [comment]
**`domain_forumsearch.py`**:
- [Line 29](https://github.com/DataSploit/datasploit/blob/master/domain_forumsearch.py#L29)

**`domain_GooglePDF.py`**:
- [Line 39](https://github.com/DataSploit/datasploit/blob/master/domain_GooglePDF.py#L39)
