### ISSUE TITLE
Problem with installation of requirements on Ubuntu 14.04

### ISSUE THREAD

**Issue by wklm** [DataSploit/datasploit#31]
Hey, while trying to install, I'm getting the following error message:

$ sudo pip install -r requirements.txt
The directory '/home/wklm/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/home/wklm/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting amqp==1.4.9 (from -r requirements.txt (line 1))
  Downloading amqp-1.4.9-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 53kB 717kB/s 
Collecting anyjson==0.3.3 (from -r requirements.txt (line 2))
  Downloading anyjson-0.3.3.tar.gz
Collecting BeautifulSoup==3.2.1 (from -r requirements.txt (line 3))
  Downloading BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-t9x02kuf/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-t9x02kuf/BeautifulSoup

How can I deal with that? 
cheers, wklm

**Comment by 0xbadshah** [comment]
May I know which version of Python you are using ?

**Comment by michael-bey** [comment]
BeautifulSoup3 is not Python 3 compatible. I think that's your issue. You can try it with a virtualenv.

**Comment by wklm** [comment]
Hey @Chan9390 @benichmt1 thanks for your prompt replies. 
I'm using Python 2.7.6, so it shouldn't be an issue :)

**Comment by upgoingstar** [comment]
Please use python version 2.7 (lot of libraries we use do not support python 3.0 so,...)
