### ISSUE TITLE
JigSaw API Key

### ISSUE THREAD

**Issue by SethCalkins** [DataSploit/datasploit#32]
I have a data.com username / password, with available tokens ... How do I retrieve my API key?

**Comment by blahdidbert** [comment]
According to Jigsaw's Community page, only customers have the ability to request API keys:

http://community.jigsaw.com/t5/API/API-Tokens-Customers-Only-Connect-Plus-plan-min/td-p/244055

> We're currently providing API access to Customers with Connect Plus plans and up.
