### ISSUE TITLE
not able to use shodan / value error:not json object could be decoded

### ISSUE THREAD

**Issue by parrotcartot** [DataSploit/datasploit#37]
Hey guys, 

I just set up datasploit on kali linux and I am facing an issue with shodan. I made a screenshot below. 

Has someone maybe had the same error? 

I would be glad for some advice, thanks!

<img width="690" alt="bildschirmfoto 2016-08-15 um 16 04 30" src="https://cloud.githubusercontent.com/assets/21039997/17667931/55e4c9c2-6307-11e6-86a3-0a53712154e1.png">

**Comment by 0xbadshah** [comment]
Hi @parrotcartot , thanks for raising the issue. From the error it is not clear what was the exact error (maybe some kind of logical error). If possible please _try to reproduce the error_ **OR** please _use the script_ `test.py` at https://gist.github.com/Chan9390/bfe2a7efca609d95171dde99793cfc22. (Make sure you use the code in datasploit directory, where the Shodan creds are present. Dont worry, its just a modified code which uses simplejson to get the exact error). Then _comment your error again_.

Will try to resolve the error as soon as possible !!! :)

**Comment by parrotcartot** [comment]
Hi Chan, 
I ran the script test.py in the datasploit directory and this is what I got: 

![bildschirmfoto 2016-08-16 um 10 42 49](https://cloud.githubusercontent.com/assets/21039997/17693296/6ae80f54-639e-11e6-9437-a0d2f83d51b3.png)

**Comment by 0xbadshah** [comment]
Run `test.py` with the arguments... `test.py` is a copy of `domainOsint.py`. So **provide the URL** of the website and just **send the screenshot of the error** (If you dont want to reveal the website which you are targeting, dont include the arguements in the screenshot).

**Comment by parrotcartot** [comment]
ok, so it spits out this error:  
![bildschirmfoto 2016-08-16 um 13 01 12](https://cloud.githubusercontent.com/assets/21039997/17696881/b024c842-63b1-11e6-92da-31ca7a07984c.png)

**Comment by 0xbadshah** [comment]
Have you correctly configured the credentials of Shodan in `config.py` ?

**Comment by 0xbadshah** [comment]
I suggest you to check the Shodan credentials correctly configured at `config.py` (Remainder: you have to enter credentials at `config.py` not `sample_config.py`). If everything is done correctly, then again download the script from https://gist.github.com/Chan9390/bfe2a7efca609d95171dde99793cfc22 and check if it works (I have again made some changes, I think it could be utf-8 decoding error, but anyways lets see...)

**Comment by parrotcartot** [comment]
So, I checked the shodan API 3 times, and the last time I realized a typo .... 

It works fine now : ) thanks a lot for your time!

**Comment by 0xbadshah** [comment]
Are you sure the **issue is resolved** ? Please close the issue.
