### ISSUE TITLE
Installation error (inotify is not available on macosx-10.11-intel)

### ISSUE THREAD

**Issue by Metnew** [DataSploit/datasploit#39]
<pre>Collecting pyinotify==0.9.6 (from -r requirements.txt (line 19))
  Using cached pyinotify-0.9.6.tar.gz
    Complete output from command python setup.py egg_info:
    inotify is not available on macosx-10.11-intel
    ---------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/dj/m0m8d52n03v4wfd7zk35fwnm0000gn/T/pip-build-DfhEUn/pyinotify/</pre>

**Comment by konradstrachan** [comment]
Same problem here but on Windows - inotify appears to only be available on Linux. As a work around I suggest removing the line from requirements.txt as it doesn't currently appear to be used anyway.

**Comment by njorobeast** [comment]
nice

**Comment by 0xbadshah** [comment]
Hey @konradstrachan Did you try installing pyinotify in [Cygwin](https://www.cygwin.com/) on Windows ?
