### ISSUE TITLE
Duplicates python scripts

### ISSUE THREAD

**Issue by n0skill** [DataSploit/datasploit#42]
The python scripts are both in the root directory and in core/osint.

It would be easier if both could be stored in a single place.

**Comment by 0xbadshah** [comment]
Hi @n0skill , there is some development going around to make Datasploit scripts run with a browser (for a better UI). If you want to see that, you could execute command: `python manage.py runserver` in the `core` directory and browse the contents (`127.0.0.1:8000`). The web view is just started and not fully developed, but will be one of the interesting features in the future releases. So the **scripts in `core` is not duplicate**. 

I suggest you to close the issue.

**Comment by n0skill** [comment]
Hello and thanks for your input.

I understand your point, but it seems that there should be a way to use the original scripts (at the root of the project) for the new UI. I understand it is not critical at that point but it will make the project less messy and so it will be easier to maintain. 

I will see if I can find a way (for instance, putting all the scripts in a dedicated folder) to be used by both a CLI user and another user using a web browser.

I'll try to do a pull request if I come up with an intelligent way to do so. If not, I'll close the issue as it is not critical at all.

Thanks anyway !

**Comment by upgoingstar** [comment]
@n0skill completely agreed with your point. I am on leaves for few days. once I am back, thats the plan. 

Have all the scripts in one place and called from there. This will picked up in this phase for sure. I would love to see if you can suggest a way to do so. We are also brainstorming the same at the moment.

**Comment by upgoingstar** [comment]
Core is gone now. :)

**Comment by n0skill** [comment]
Nice ! Sorry for not submitting any pull requests, I've been busy studying 😄
