### ISSUE TITLE
Handling commandline arguments

### ISSUE THREAD

**Issue by 0xbadshah** [DataSploit/datasploit#49]
There is **no check** if the **required arguments** are given by the user and is not handled even in other modular scripts.

For example,

```
datasploit@datasploit $ python domainOsint.py
Traceback (most recent call last):
  File "domainOsint.py", line 72, in <module>
    from emailOsint import print_emailosint
  File "/home/datasploit/emailOsint.py", line 17, in <module>
    email = sys.argv[1]
IndexError: list index out of range
```

**Comment by SudhanshuC** [comment]
@Chan9390 Thanks for pointing this out. We will be working on exception handling for the whole project. Expect something by the end of Sep First week.

**Comment by upgoingstar** [comment]
Opened as #80. I know I am behind schedule and will try to expedite the same. :)
