### ISSUE TITLE
Pointing to a possible documentation error in Setup Guide - Step 4 

### ISSUE THREAD

**Issue by abhijitmishra87** [DataSploit/datasploit#51]
http://datasploit.readthedocs.io/en/latest/setupGuide/

Step 4: Generate API Keys and paste inside **config_sample.py**

Generate API keys using the api Key Generation guide at

http://datasploit.readthedocs.io/en/latest/apiGeneration/

and enter the respective values in **config.py** file. Leave all other key value pairs blank.

Step 3 makes us rename config_sample.py to config.py, so I believe the header needs to be changed

**Comment by upgoingstar** [comment]
nice catch bud. Done. :)

**Comment by abhijitmishra87** [comment]
Cheers.
