### ISSUE TITLE
Error Finding hosts from ZoomEye

### ISSUE THREAD

**Issue by SaiGonSeamus** [DataSploit/datasploit#55]
I have followed the instructions correctly, tried with 2 different email accounts

keep getting "please enter correct verify code" on the telent 404 site and then this when I run domainOsint.py

---> Finding hosts from ZoomEye

Traceback (most recent call last):
  File "domainOsint.py", line 435, in <module>
    main()
  File "domainOsint.py", line 431, in main
    do_everything(domain)
  File "domainOsint.py", line 337, in do_everything
    zoomeye_results = search_zoomeye(domain)
  File "/root/datasploit-master/domain_zoomeye.py", line 25, in search_zoomeye
    zoomeye_token = get_accesstoken_zoomeye(domain)
  File "/root/datasploit-master/domain_zoomeye.py", line 18, in get_accesstoken_zoomeye
    access_token1 = responsedata['access_token']
KeyError: 'access_token'

**Comment by 0xbadshah** [comment]
Are you sure if the `access_token` is correctly entered in `config.py`?

**Comment by SaiGonSeamus** [comment]
I can't seem to get it to activate on the site, tried 2 browsers, followed the instructions.

Anyone else have problems?

Can I just comment out a few lines of code to get round this for the time being and continue testing?

**Comment by beakman** [comment]
I solved this problem changing my password. Apparently the JSON passed to the api  endpoint don't accept special characters.

`curl -H "Content-Type: application/json" -X POST -d '{"username":"YOUR_EMAIL","password":"ONLY_LETTERS_AND_NUMBERS"}' https://api.zoomeye.org/user/login`

**Comment by SaiGonSeamus** [comment]
I've tried it with 3 serperate passwords with no special characters. Same thing. I'm stumped.

To sanity check 

"Once you fill the email id in the second text box, click on send activation code"

means the email address that you signed up right?

**Comment by SaiGonSeamus** [comment]
The confirmation emails are taking longer to arrive than the 5 minutes the token is valid for. I think this may be the reason, they might be getting caught in a spam filter.

**Comment by beakman** [comment]
Yes, I found some troubles to activate my account (the activation code doesn't arrive). I tried a few times until the code arrived and the website accepted it. @SaiGonSeamus, it still asking you for an activation code? 

FYI, I registered with an outlook.com account.

**Comment by ebrinkster** [comment]
I was having issues with this until I did what @beakman recommended.  Changed password to non-special characters.  Works like a charm.  @SaiGonSeamus The activation code worked fine for me, took a couple of minutes but ended up in my inbox.

**Comment by SaiGonSeamus** [comment]
Finally fixed it. it was special characters first, then the delay in receiving the email which is only valid for 5 minutes.  Mine was taking up to 17 mins at one domain.

Thanks for the help, that was bugging me.

**Comment by SaiGonSeamus** [comment]
Even though I have now got the code to activate on the site, I'm still getting the original error on yet another new build.

Is Zoomeyeuser the email address or the username?

Is Zoomeyepass the code that arrives by email or the password used to register with telent.

I've tried every combination.

**Comment by blahdidbert** [comment]
@SaiGonSeamus 

According to the Zoomeye API documentation:
https://www.zoomeye.org/api/doc#user

| Parameters Name | Type | Description | Required? | Example |
| --- | --- | --- | --- | --- |
| **username** | string | username(mail) | required | **foo@bar.com** |
| **password** | string | password | required | **foopass** |

**Comment by SaiGonSeamus** [comment]
Thanks for this, I had a look at this myself. Still same error. I think at this stage I'll suspend testing this until some more work has been done on it. Taking up too much time.

**Comment by SaiGonSeamus** [comment]
This is now working. Changed password again.
