### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by ckennard** [DataSploit/datasploit#56]
Hi, I'm having a JSON problem when I try to run this tool on my own domain. I have included the complete log here: 

chriskennard@mint ~/Desktop/tools/datasploit $ python domainOsint.py -d chriskennard.com

```
  ____/ /____ _ / /_ ____ _ _____ ____   / /____  (_)/ /_
  / __  // __ `// __// __ `// ___// __ \ / // __ \ / // __/
 / /_/ // /_/ // /_ / /_/ /(__  )/ /_/ // // /_/ // // /_  
 \__,_/ \__,_/ \__/ \__,_//____// .___//_/ \____//_/ \__/  
                               /_/                        

           Open Source Assistant for #OSINT            
                 website: www.datasploit.info               
```

No earlier scans found for chriskennard.com, Launching fresh scan in 3, 2, 1..

---> Finding Whois Information.
{
  "updated_date": [
    "2016-07-28 00:00:00", 
    "2016-07-28 07:00:00"
  ], 
  "status": [
    "clientTransferProhibited https://icann.org/epp#clientTransferProhibited", 
    "clientTransferProhibited https://www.icann.org/epp#clientTransferProhibited"
  ], 
  "name": "Contact Privacy Inc. Customer 12435752", 
  "dnssec": "unsigned", 
  "city": "Toronto", 
  "expiration_date": [
    "2017-01-26 00:00:00", 
    "2017-01-26 08:00:00"
  ], 
  "zipcode": "M4K 3K1", 
  "domain_name": [
    "CHRISKENNARD.COM", 
    "chriskennard.com"
  ], 
  "country": "CA", 
  "whois_server": "whois.google.com", 
  "state": "ON", 
  "registrar": "Google, Inc.", 
  "referral_url": "http://domains.google.com", 
  "address": "96 Mowat Ave", 
  "name_servers": [
    "NS-CLOUD-E1.GOOGLEDOMAINS.COM", 
    "NS-CLOUD-E2.GOOGLEDOMAINS.COM", 
    "NS-CLOUD-E3.GOOGLEDOMAINS.COM", 
    "NS-CLOUD-E4.GOOGLEDOMAINS.COM"
  ], 
  "org": "Contact Privacy Inc. Customer 12435752", 
  "creation_date": [
    "2015-01-26 00:00:00", 
    "2015-01-26 08:00:00"
  ], 
  "emails": [
    "registrar-abuse@google.com", 
    "mjtksenlzfop@contactprivacy.email"
  ]
}
---> Finding Whois Information.

A Records
    216.239.32.21
    216.239.34.21
    216.239.36.21
    216.239.38.21
MX Records
    5 gmr-smtp-in.l.google.com.
    10 alt1.gmr-smtp-in.l.google.com.
    20 alt2.gmr-smtp-in.l.google.com.
    30 alt3.gmr-smtp-in.l.google.com.
    40 alt4.gmr-smtp-in.l.google.com.
SOA Records
    ns-cloud-e1.googledomains.com. dns-admin.google.com. 14 21600 3600 1209600 300
Name Server Records
    ns-cloud-e1.googledomains.com.
    ns-cloud-e2.googledomains.com.
    ns-cloud-e3.googledomains.com.
    ns-cloud-e4.googledomains.com.
TXT Records
    No Records Found
CNAME Records
    No Records Found
AAAA Records
    2001:4860:4802:32::15
    2001:4860:4802:34::15
    2001:4860:4802:36::15
    2001:4860:4802:38::15

---> Trying luck with PunkSpider

[-] No Vulnerabilities found on PunkSpider

---> Wappalyzing web pages

->Trying Wapalyzer on HTTP: 
[-] HTTP connection was unavailable
->Trying Wapalyzer on HTTPS: 
[-] HTTP connection was unavailable

---> Searching Github for domain results

Sad! Nothing found on github

---> Harvesting Email Addresses:.

[u'status', u'domain', u'pattern', u'results', u'webmail', u'offset', u'emails']

Do you want to launch osint check for these emails? [(Y)es/(N)o/(S)pecificEmail]: y

---> Searching Domain history in Netcraft

216.239.36.21: Google Inc

---> Finding Pagelinks:

no links found
zero subdomains found here
---> Finding subdomains: 

---> Searching through WikiLeaks

Total 
0 results 

For all results, visit: https://search.wikileaks.org/?query=&exact_phrase=chriskennard.com&include_external_sources=True&order_by=newest_document_date

---> Gathering links from Forums:

---> Performing passive SSL Scan

Traceback (most recent call last):
  File "domainOsint.py", line 432, in <module>
    main()
  File "domainOsint.py", line 428, in main
    do_everything(domain)
  File "domainOsint.py", line 291, in do_everything
    results = check_ssl_htbsecurity(domain)
  File "/home/cnkennar/Desktop/tools/datasploit/domain_sslinfo.py", line 16, in check_ssl_htbsecurity
    results = json.loads(req.content)
  File "/usr/lib/python2.7/json/**init**.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ckennard** [comment]
<del>I also receive a similar error after patching the SSL Scan option.
<del>---> Searching in Shodan:

<del>Traceback (most recent call last):
<del>  File "domainOsint.py", line 432, in <module>
<del>    main()
<del>  File "domainOsint.py", line 428, in main
<del>    do_everything(domain)
<del>  File "domainOsint.py", line 382, in do_everything
<del>    res_from_shodan = json.loads(shodandomainsearch(domain))
<del>  File "/usr/lib/python2.7/json/**init**.py", line 339, in loads
<del>    return _default_decoder.decode(s)
<del>  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
<del>    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
<del>  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
<del>    raise ValueError("No JSON object could be decoded")
<del>ValueError: No JSON object could be decoded

Nevermind this message, I had the wrong API key in config.py

**Comment by upgoingstar** [comment]
This is same as #68
