### ISSUE TITLE
Initialization error with email0sint.py

### ISSUE THREAD

**Issue by cabdalla** [DataSploit/datasploit#58]
Running Mint 18 and getting strange issues on initilization:

python domainOsint.py 
Traceback (most recent call last):
  File "domainOsint.py", line 72, in <module>
    from emailOsint import print_emailosint
  File "/home/foo/datasploit/emailOsint.py", line 17, in <module>
    email = sys.argv[1]
IndexError: list index out of range

running python 2.7.12

Thanks.

**Comment by cabdalla** [comment]
Never mind. I didn't add the flag. Duh. Sorry.

**Comment by 0xbadshah** [comment]
You have to enter the domain name along with the name of script in terminal. The apt usage is : `python domainOsint.py -d domain.org`
