### ISSUE TITLE
Getting random "Please check if Email_id exist or not?"

### ISSUE THREAD

**Issue by Stepkaa** [DataSploit/datasploit#60]
Sometimes running for example `python emailOsint.py somemail@gmail.com` I'm getting 
`[-] Error Occured - Encountered Status Code: 404. Please check if Email_id exist or not?` or 
`[-] Error Occured - Encountered Status Code: 202. Please check if Email_id exist or not?`

Why does this happen? Sometimes it runs, sometimes it doesn't.

**Comment by ebrinkster** [comment]
+1 I am encountering this issue as well.

**Comment by SaiGonSeamus** [comment]
as am I.

**Comment by upgoingstar** [comment]
Hi, This is a genuine problem. We are using fullcontact as thirs party api here and lookup emails through their APIs. 

Most of the time they have some data related that email_address in their DB, but when they dont have, they give us 404 with the error 'Please check if Email_id exist or not?'

As of now I dont have any solution for this except for looking for other such APIs and integrate them too.  :)

Let me know if you guys know any such APIs.
