### ISSUE TITLE
ImportError: No module named whois

### ISSUE THREAD

**Issue by enamds** [DataSploit/datasploit#62]
Hi, I using Ubuntu 15 and python 3. So a have an issue when trying 
`python domainOsint.py -d domain.org`
an answer is 

```
Traceback (most recent call last):
  File "domainOsint.py", line 30, in <module>
    import whois
ImportError: No module named whois
```

Can u help me? What I doing wrong?

**Comment by 0xbadshah** [comment]
Same as issue #46 . Try executing `pip install python-whois==0.6.2`

**Comment by enamds** [comment]
TY for answer, now error is

```
File "domainOsint.py", line 35, in <module>
    from Wappalyzer import Wappalyzer, WebPage
ImportError: No module named Wappalyzer
```

**Comment by 0xbadshah** [comment]
Did you actually install all the requirements ? ( I doubt it ). Just install all the modules listed in `requirements.txt` using the command `pip install -r requirements.txt`

**Comment by 0xbadshah** [comment]
Close the issue if you have everything resolved.

**Comment by upgoingstar** [comment]
Closing this as I expect this should have worked. Thanks @Chan9390 

@enamds If you are still facing the same problem, please feel free to re-open the same. Thanks.
