### ISSUE TITLE
More data than I can handle, hence not saved in MongoDb. Apologies.

### ISSUE THREAD

**Issue by SaiGonSeamus** [DataSploit/datasploit#63]
Is this a hard limit?

What do we need to do to avoid this?

**Comment by upgoingstar** [comment]
result = db.domaindata.insert(dict_to_apend, check_keys=False)

This is limit on pymongo library we are using. As of now I dont have a solution around it, but other file format outputs will soon be introduced and will help around this issue as a short term solution.

**Comment by upgoingstar** [comment]
Added as #79
