### ISSUE TITLE
SSL Scan issue

### ISSUE THREAD

**Issue by 0xbadshah** [DataSploit/datasploit#68]
As per `domain_sslinfo.py`, the passive SSL scan is conducted with the help of the site www.htbridge.com
But the website currently has some certificate error when viewed in a browser. Chrome displays the following: 

> This server could not prove that it is **www.htbridge.com**; its security certificate is from **htbridge.ch**. 

Anyways there is a way to ignore verifying in Python. When we modify the [Line 25 in domain_sslinfo.py](https://github.com/upgoingstar/datasploit/blob/master/domain_sslinfo.py#L15) as:

`req = requests.post('https://www.htbridge.com/ssl/chssl/1451425590.html', headers=headers , data=data, verify=False)`

we get the response as:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /chssl/1451425590.html was not found on this server.</p>
</body></html>
```

which is html **not JSON**. So issue of `No JSON object could be decoded` arises ( Issue #67 )

**Comment by SaiGonSeamus** [comment]
I made this change but still get this

Traceback (most recent call last):
  File "domainOsint.py", line 432, in <module>
    main()
  File "domainOsint.py", line 428, in main
    do_everything(domain)
  File "domainOsint.py", line 291, in do_everything
    results = check_ssl_htbsecurity(domain)
  File "/root/datasploit/domain_sslinfo.py", line 16, in check_ssl_htbsecurity
    results = json.loads(req.content)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by 0xbadshah** [comment]
Please upload the file with changes and comment the link below.

**Comment by SaiGonSeamus** [comment]
I think you mean line 15, not 25.

This is the latest version.

This is the error.

---> Performing passive SSL Scan

Traceback (most recent call last):
  File "domainOsint.py", line 435, in <module>
    main()
  File "domainOsint.py", line 431, in main
    do_everything(domain)
  File "domainOsint.py", line 291, in do_everything
    results = check_ssl_htbsecurity(domain)
  File "/root/datasploit/domain_sslinfo.py", line 16, in check_ssl_htbsecurity
    results = json.loads(req.content)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

[domain_sslinfo.py.zip](https://github.com/upgoingstar/datasploit/files/528935/domain_sslinfo.py.zip)

**Comment by Dargin** [comment]
It looks like the API for htbridge has changed, here is what i did to fix it.

In domain_sslinfo.py change the req = requests.post to 
req = requests.post('https://www.htbridge.com/ssl/api/v1/check/1451425590.html', headers=headers , data=data)

api/v1/check appears to be the new path. Also the format that comes back into json has changed, i changed my main function and the one in domainOsint.py as follows. I commented out the VALUE section as it appears that no longer exists - need to dig through the new results to see what's useful:

else:
        print "OverAll Rating: %s" % results['results']['grade']
        #for x in results['VALUE'].keys():
        #   if str("[5]") in str(results['VALUE'][x]) or str("[3]") in str(results['VALUE'][x]):
        #       if x == 'httpHeaders':
        #           pass
        #       else:
        #           print results['VALUE'][x]

**Comment by upgoingstar** [comment]
As I was not finding it much useful, I have removed the same for some time. Will benchmark results from them and other such services and then write the module accordingly.
