### ISSUE TITLE
Overall bugs in datasploit

### ISSUE THREAD

**Issue by 0xbadshah** [DataSploit/datasploit#70]
Did a source code analysis and found the following bugs in Datasploit : 
### `active_default_file_check.py`
- [ ] `host` is blindly suffixed with `http://` without checking if host already contains `http://`
- [ ] No check for _Redirection_
- [ ] [Line 35](https://github.com/upgoingstar/datasploit/blob/master/active_default_file_check.py#L35) is not necessary as there is no check for `403 Forbidden` or any other _specific error codes_

**Logical Errors:**
- [ ] If `status_code` for a non-existent page is 200, then all the existing pages will be rejected
- [ ] The returned `status_code` could be _301 Redirect_, but it will be added as `base_statuscode` i.e. code returned for non-existent page

---
### `domain_censys.py`
- [ ] As far as the output is concerned, results are given out as a list to the user.

---
### `domain_checkpunkspider.py`
- [ ] Python connection warnings are ignored, _requests_ explicitly has `verify=False`

**Suggestions:**
- Give an output if the module didn't work.

---
### `domain_dnsrecords.py`

---
### `domain_emailhunter.py`

---
### `domain_forumsearch.py`

---
#### Not developed fully

---
#### Not working - not developed fully

---
### `domain_history.py`

---
### `domain_pagelinks.py`

---
### `domain_shodan.py`

---
### `domain_sslinfo.py`
- [ ] `HTML` mishandled as `JSON` when the output is _Not Found_ ( Issue #68 )
- [ ] URL used in [Line 15](https://github.com/upgoingstar/datasploit/blob/master/domain_sslinfo.py#L15) returns `404 - Not Found` which makes the script as **Not Working** ( Issue #54 )

---
### `domain_subdomains.py`
- [x] `find_subdomains_from_wolfram(domain)` in [Line 50](https://github.com/upgoingstar/datasploit/blob/master/domain_subdomains.py#L50) is not working as of now. **Needs development**

**Others:**
- Interesting issue #66 
- [Line 172](https://github.com/upgoingstar/datasploit/blob/master/domain_subdomains.py#L172) states _Zero subdomains found here_. It would be better if you check if there are subdomains other than the main domain before displaying. Example if no subdomains are found, the output will be 

> ---> Finding subdomains, will be back soon with list. 
> zero subdomains found here
> List of subdomains found
> REDACTED_DOMAIN.com

---
### `domain_wappalyzer.py`

---
### `domain_whois.py`

---
### `domain_wikileaks.py`

---
### `domain_zoomeye.py`

---
### `domainOsint.py`

---
### `email_fullcontact.py`

---
### `emailOsint.py`

---
### `facebook_user_details.py`
- [ ] Handle JSON and display the specific user information **Development Required**
- [ ] Check if the `username` is present and handle error if not present

---
### `generate_passwords.py`
- No bugs, **development required**
- **NOT RECOMMENDED**

---
### `git_searcher.py`
- [ ] Check if the user is valid
- [ ] Output relevant information, not yet fully developed (**Development Required**)

---
### `instaUsernameOsint.py`
- [ ] [Line 12](https://github.com/upgoingstar/datasploit/blob/master/instaUsernameOsint.py#L12) uses `cfg.instagram_token` whereas `instagram_token` is not present in `config_sample.py`. Instead `instagram_api` is present in `config_sample.py`

---
### `ip_shodan.py`
- [ ] Handle JSON response
- **Not used by any script**

---
### `ip_to_neighboursites.py`
- No bugs
- **Not used by any script**

---
### `usernameOsint.py`
- [ ] [Line 35](https://github.com/upgoingstar/datasploit/blob/master/usernameOsint.py#L35) explicitly uses `verify=False` which means the SSL connection is ignored even if there is an error

**Others:**
- [x] Not completely developed. Explicitly used GitHub actions against a user (@anantshri) as an example in comments

---
### Overall bugs
- [ ] No checking if `sys.argv[1]` is present
- [ ] Colored output is not used in all scripts
- [ ] No checking for API keys which are mandatory for some modules to work.
### All these bugs will be removed / reduced in the upcoming pull requests

[ **NOTE :** Scripts in `core` directory were not checked ]

**Comment by 0xbadshah** [comment]
@upgoingstar 
- removed junk lines in `usernameOsint.py` [ **commit :** e20707f ]
- removed subdomains bug [ **commit :** ae5ca68 ]

**Comment by 0xbadshah** [comment]
### emailOsint.py

`clearbit(email)` is not used in `emailOsint.py` but Clearbit API is mentioned in `config_sample.py`. Please mention it explicitly while users are creating API key as there is no use of creating one as of now.

**Comment by 0xbadshah** [comment]
### ip_shodan.py

`domaintoip(domain)` in [Line 72](https://github.com/DataSploit/datasploit/blob/master/ip_shodan.py#L72) is never used.

**Comment by djtroby** [comment]
Hi.....getting the below error...
root@kali:~/datasploit# python domainOsint.py -d datasploit.info 
Traceback (most recent call last):
  File "domainOsint.py", line 6, in <module>
    import whois
ImportError: No module named whois
root@kali:~/datasploit# python domain0sint.py -d sternon.com    
python: can't open file 'domain0sint.py': [Errno 2] No such file or directory
root@kali:~/datasploit# python domainOsint.py -d sternon.com 
Traceback (most recent call last):
  File "domainOsint.py", line 6, in <module>
    import whois
ImportError: No module named whois
root@kali:~/datasploit# 
The network connection was aborted by the local system.

**Comment by 0xbadshah** [comment]
Closing the issue. Newer one coming soon !
