### ISSUE TITLE
Check osintframework.com

### ISSUE THREAD

**Issue by 0xbadshah** [DataSploit/datasploit#72]
The site http://osintframework.com/ has lots of good resources for OSINT. I think most of them could be included to datasploit.

[ The project is also open source, you could find the source code of the website at https://github.com/lockfale/OSINT-Framework ]

**Comment by upgoingstar** [comment]
Yes, I had look on them. While many of them are interesting, unfortunately API support isnt there and dont really want to scrape things further. :P 

I am however looking for more resources around IP and email IDs to work a bit more in that direction. 

Thanks.
