### ISSUE TITLE
Can you guys help me?

### ISSUE THREAD

**Issue by ghost** [DataSploit/datasploit#74]

**Comment by 0xbadshah** [comment]
Try this command `sudo service mongodb status` and _reply the output_

**Comment by thrilos100** [comment]
Thanks a lot man,i have one more question,is this okey,or i have some problems with my files on datasploit or either my connection?

---> Trying luck with PunkSpider

[-] No Vulnerabilities found on PunkSpider

---> Wappalyzing web pages

->Trying Wapalyzer on HTTP: 
[-] HTTP connection was unavailable
->Trying Wapalyzer on HTTPS: 
[-] HTTP connection was unavailable

**Comment by 0xbadshah** [comment]
I can't blindly decide what's the error. It could be either error in the connection or in the logic of the script. I have created a gist of the `domainOsint.py`. I have changed two lines to get the error. So **download the file `datasploit_test.py`**, place it in the datasploit folder and run it. Then **comment the detailed error.** 

Link of the file: https://gist.github.com/Chan9390/7ee8b0c46cd16bbf1e8136639db0a6bf

**Comment by thrilos100** [comment]
I run it and i got these errors

python datasploit_test.py 
Traceback (most recent call last):
  File "datasploit_test.py", line 72, in <module>
    from emailOsint import print_emailosint
  File "/root/Desktop/datasploit/emailOsint.py", line 17, in <module>
    email = sys.argv[1]
IndexError: list index out of range

**Comment by 0xbadshah** [comment]
You didn't provide the domain. Please provide the domain you want to test, example `python datasploit_test.py xyz.com`. After that comment the errors which you get.

**Comment by thrilos100** [comment]
amm,actually the test went very well,i got all scans,but in the end i got these errors

---> Performing passive SSL Scan

Traceback (most recent call last):
  File "datasploit_test.py", line 434, in <module>
    main()
  File "datasploit_test.py", line 430, in main
    do_everything(domain)
  File "datasploit_test.py", line 290, in do_everything
    results = check_ssl_htbsecurity(domain)
  File "/root/Desktop/datasploit/domain_sslinfo.py", line 16, in check_ssl_htbsecurity
    results = json.loads(req.content)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by 0xbadshah** [comment]
The initial error you got may be because of:
- error in internet connection
- the site may be down

**Comment by thrilos100** [comment]
@Chan9390 Thanks a lot for your help dude,i appreciate that!

**Comment by 0xbadshah** [comment]
Just delete datasploit_test.py, it was just a temporary file to now the error. And also don't forget to close the issue.

**Comment by upgoingstar** [comment]
@thrilos100 : I am closing this one. If you are still facing the same problem, please feel free to re-open the same. Thanks.
