### ISSUE TITLE
Performing passive SSL Scan

### ISSUE THREAD

**Issue by FreelancePentester** [DataSploit/datasploit#77]
Performing passive SSL Scan

Traceback (most recent call last):
  File "domainOsint.py", line 435, in <module>
    main()
  File "domainOsint.py", line 431, in main
    do_everything(domain)
  File "domainOsint.py", line 311, in do_everything
    print "OverAll Rating: %s" % results['GRADE']
KeyError: 'GRADE'

**Comment by 0xbadshah** [comment]
As the API of htbridge.com is changed, the old code doesn't work now. The new code is under review ( if you want to see check PR #76 ).

**Comment by upgoingstar** [comment]
API is broken, and hence I am pulling this module off. Please git pull for the latest code.

**Comment by upgoingstar** [comment]
Another reason to pull this off was I did not found this very useful. 

@FreelancePentester : let me know if you have some usecase around this and I would love to include it back.
