### ISSUE TITLE
Error in domain_censys.py

### ISSUE THREAD

**Issue by ameygat** [DataSploit/datasploit#8]
Parsed and collected results from page 1
Traceback (most recent call last):
  File "domain_censys.py", line 70, in <module>
    main()
  File "domain_censys.py", line 64, in main
    censys_search(domain)
  File "domain_censys.py", line 15, in censys_search
    res = requests.post("https://www.censys.io/api/v1/search/ipv4", json = params, auth = (cfg.censysio_id, cfg.censysio_secret))
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, *_kwargs)
TypeError: request() got an unexpected keyword argument 'json'

**Comment by upgoingstar** [comment]
Which request version are you using? I am using 2.9.1 which is supposed to handle json keyword in requests library. Can you upgrade? 

> > > import requests
> > > requests.**version**
> > > '2.9.1'

I will add this in requirements too. Thanks for pointing out :)

**Comment by ameygat** [comment]
Mine requests.version is 2.2.1

**Comment by upgoingstar** [comment]
ya, thats the reason i think. later versions of requests added support for json keyword. Please update and check if its working.
