### ISSUE TITLE
Add metadata module

### ISSUE THREAD

**Issue by upgoingstar** [DataSploit/datasploit#86]

**Comment by 0xbadshah** [comment]
Can you be brief about the module ?

**Comment by upgoingstar** [comment]
I plan to enumerate a list of files related to a domain and then extract metadata from these files. 

Since it will involve direct hits to the websites, this will be available as standalone script with a small warning of active involvement with the target.

**Comment by 0xbadshah** [comment]
A standalone version is good at the initial stage. But I would suggest to make it flexible so that it could be integrated into the main python script and could be called under a command-line tag like `--activeScan`.

**Comment by upgoingstar** [comment]
True, once we have more active scan scripts in the kit..

**Comment by upgoingstar** [comment]
We have decided not to put lot of active scans in datasploit, as this will move us from the objective of the tool. Instead, writing another tool which consume datasploit's output will be more effective way.
