### ISSUE TITLE
CLI data to MongoDB

### ISSUE THREAD

**Issue by pulporange** [DataSploit/datasploit#88]
Hi there
At first, i want to take the time to thank you for sharing this tool with the community
 
I'm using the CLI tool **domainOsint.py** script to gather the data but apparently nothing is inserted in the MongoDB.
Is the note on the script itself saying that the MongoDB support has been dropped at least on the CLI is it correct ?

Here is my setup, i've follow the requirements for CLI only (no rabbitmq, no django)

- Ubuntu 16.04
- MongoDB 3.4 running on the specified Directory
- I was able to create an entry on a DB with no problem (confirmed by the logs)

btw everything is working on the API side except the google_cse_*, i've bee able to find other sources of intel on pastebin etc..

Thanks for your help

**Comment by 0xbadshah** [comment]
The MongoDB feature is currently stopped and will not be developed in future releases. Instead the upcoming versions ( as per @upgoingstar vision ) will have extended output features like output the data in CSV and JSON formats.

**Comment by upgoingstar** [comment]
We have html and json output formats now. As mentioned by @Chan9390 , gui is no more supported. Please refer to latest documentation at https://datasploit.github.io/datasploit/.

We will try to get the csv thing sorted out soon, if that looks useful.
