### ISSUE TITLE
error in domain_emailhunter.py

### ISSUE THREAD

**Issue by B4RD4k** [DataSploit/datasploit#9]
When running the tool against the domain, I'm getting this error 
AttributeError: 'module' object has no attribute 'emailhunter'

Looks like it has the error when trying to fetch information from Github.com

**Comment by SudhanshuC** [comment]
It could be that you have not configured 'config.py' with the parameter 'emailhunter'. I suggest you to register an account at https://emailhunter.co/ and put the API key (find here https://emailhunter.co/api_keys) in the config file.

E.g. Add this to config.py--> emailhunter="YOUR_API_KEY_HERE"
