### ISSUE TITLE
usernameOsint - TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by johnlittle4550** [DataSploit/datasploit#94]
root@nethunterarch:/opt/datasploit# python usernameOsint.py jwlittle
			[+] Checking git user details

Login: jwlittle
avatar_url: https://avatars.githubusercontent.com/u/2593652?v=3
id: 2593652
Repos: https://api.github.com/users/jwlittle/repos
Name: None
Company: None
Blog: None
Location: None
Hireable: None
Bio: None
On GitHub: 2012-10-18T23:03:46Z
Last Activity: 2016-02-27T04:05:06Z

-----------------------------

			[+] Username found on:

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
http://gravatar.com/jwlittle
http://jwlittle.deviantart.com/
http://www.etsy.com/people/jwlittle
http://en.wikipedia.org/wiki/User:jwlittle
http://videobam.com/users/jwlittle
http://www.last.fm/user/jwlittle
https://www.pinterest.com/jwlittle
http://twitter.com/jwlittle
http://www.myfitnesspal.com/user/jwlittle/status
http://www.tripadvisor.co.uk/members/jwlittle
http://www.ebay.com/usr/jwlittle
http://community.spotify.com/t5/forums/searchpage/tab/user?q=jwlittle
http://www.photobucket.com/user/jwlittle/library

-----------------------------

Traceback (most recent call last):
  File "usernameOsint.py", line 304, in <module>
    imagelinks=profilepic(links)
  File "usernameOsint.py", line 136, in profilepic
    extracting(url,tg,att,val,valx,pro)
  File "usernameOsint.py", line 47, in extracting
    imglinks.append(img[finattrib])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by upgoingstar** [comment]
I believe this is solved now, can you confirm and reopen the issue if the problem persists?
