### ISSUE TITLE
Suggestion: Docker setup

### ISSUE THREAD

**Issue by d9j** [DataSploit/datasploit#96]
Hey.. It looks like requires some complex setup environment. it would be great if there was available a docker image(drbian based or your choice). P.s It's just a suggestion :)

**Comment by 0xbadshah** [comment]
Hey @LinkedHK have a look at https://hub.docker.com/r/appsecco/datasploit/
It is a Ubuntu 16.04 container which comes with all the required dependencies.

*(If you think that you found the solution, please close the issue)*.
